name: Preview Flutter Web
on:
  push:
    branches:
      - v2-dev

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --only hosting:mohamed-portfolio-v2